// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmnibipwohhmnjyrnvll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtbmliaXB3b2hobW5qeXJudmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzk3MTIsImV4cCI6MjA2NTUxNTcxMn0.Dup_DSyAXxrXibCdOQmwR1kMajYNT953fvLSXp1GFlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);